/// Flutter icons Turkeyflag
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Turkeyflag
///      fonts:
///       - asset: fonts/Turkeyflag.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Turkeyflag {
  Turkeyflag._();

  static const _kFontFam = 'Turkeyflag';
  static const String? _kFontPkg = null;

  static const IconData turkey = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
