/// Flutter icons Usa_flag
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Usa_flag
///      fonts:
///       - asset: fonts/Usa_flag.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UsaFlag {
  UsaFlag._();

  static const _kFontFam = 'Usa_flag';
  static const String? _kFontPkg = null;

  static const IconData united_states = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
